version: 0.2.0   

name: angular-azure-stack
description: A stack to deploy Angular app to Azure

branding:
  icon: 'cloud'
  color: 'red'

inputs:

  - name: AZURE_APP_NAME
    description: Enter the Azure web app name to deploy
    is-secret: false
    required: true
    
  - name: AZURE_WEBAPP_PUBLISH_PROFILE
    description: Enter the Azure web app Publish profile 
    is-secret: true
    required: true

configs:
   repo-metadata:
      parameters:
        description: 'Angular app hosted in azure'
        secrets: 
          - name: AZURE_WEBAPP_PUBLISH_PROFILE
            value: ${{inputs.AZURE_WEBAPP_PUBLISH_PROFILE}}
        topics:
        - angular
        - azure
        
   environments:                                        
    - name: development
      parameters: 
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*

init:
 uses: "stack-init.yaml"
